# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from blocksite import Blocksite
#TODO Clear entryName after press button
#TODO Add title to blocked site list
#TODO Check if script run with privilege
#TODO Check if script works fine with windows
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addFrame = QtWidgets.QFrame(self.centralwidget)
        self.addFrame.setGeometry(QtCore.QRect(0, 0, 640, 85))
        self.addFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.addFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.addFrame.setLineWidth(1)
        self.addFrame.setMidLineWidth(0)
        self.addFrame.setObjectName("addFrame")
        self.labelName = QtWidgets.QLabel(self.addFrame)
        self.labelName.setGeometry(QtCore.QRect(20, 32, 81, 17))
        self.labelName.setWordWrap(True)
        self.labelName.setObjectName("labelName")
        self.entryName = QtWidgets.QLineEdit(self.addFrame)
        self.entryName.setGeometry(QtCore.QRect(120, 25, 250, 30))
        self.entryName.setObjectName("entryName")
        self.addButton = QtWidgets.QPushButton(self.addFrame)
        self.addButton.setGeometry(QtCore.QRect(380, 25, 89, 30))
        self.addButton.setObjectName("addButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 85, 640, 371))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listOfBlockedSite = QtWidgets.QListView(self.frame)
        self.listOfBlockedSite.setGeometry(QtCore.QRect(0, 0, 640, 371))
        self.listOfBlockedSite.setObjectName("listOfBlockedSite")
        self.model = QtGui.QStandardItemModel()
        self.listOfBlockedSite.setModel(self.model)
        blockedSiteList = Blocksite().getListOfBlockedSite()
        for item in blockedSiteList:
            item = QtGui.QStandardItem(item)
            self.model.appendRow(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.addButton.clicked.connect(self.addBlockedSite)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def addBlockedSite(self):
        Blocksite().addSiteBlock(self.entryName.text())
        self.statusbar.showMessage("Site added.")
        item = QtGui.QStandardItem(self.entryName.text())
        self.model.appendRow(item)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Site Blocker"))
        self.labelName.setText(_translate("MainWindow", "Site name :"))
        self.entryName.setPlaceholderText(_translate("MainWindow", "www.example.com"))
        self.addButton.setText(_translate("MainWindow", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
